#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

sxhkd &
# Use picom compositor
picom &
redshift -l 51:7 &

# Hide x-cursor when on no window
xsetroot -cursor_name left_ptr

sh $HOME/.config/bspwm/default.sh

# Small padding on bottom
bspc config bottom_padding 1

feh --bg-fill $HOME/.config/bspwm/1.jpg
setxkbmap -layout de,de
dunst &

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true
bspc config pointer_follows_focus true

#bspc rule -a Chromium desktop=^1 follow=on
bspc rule -a Emacs state=tiled

