#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

sxhkd &
# Use picom compositor
picom &
redshift -l 51:7 &

# Hide x-cursor when on no window
xsetroot -cursor_name left_ptr

# Small padding on bottom
bspc config bottom_padding 1

sh $HOME/.screenlayout/layout.sh
feh --bg-fill $HOME/.config/i3/2.jpg
setxkbmap -layout de,de
sh $HOME/dotfiles/polybar/launch_polybar_bspwm.sh
dunst &


bspc wm -O HDMI-0 DVI-I-1 DVI-D-0

bspc monitor HDMI-0 -d 1 2 3 4
bspc monitor DVI-I-1 -d 5 6 7
bspc monitor DVI-D-0 -d 8 9 10
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true
bspc config pointer_follows_focus true

#bspc rule -a Chromium desktop=^1 follow=on
bspc rule -a Emacs state=tiled
